### ISSUE TITLE
Error on recursive XTP schema

### ISSUE THREAD

**Issue by evacchi** [dylibso/xtp-go-bindgen#14]
The following schema causes the Go backend to error out

```yaml
exports:
  transform:
    input:
      $ref: "#/components/schemas/Record"
      contentType: application/json
    output:
      $ref: "#/components/schemas/Record"
      contentType: application/json
    description: |
      This function takes a Record and returns a Record.
version: v1-draft
components:
  schemas:
    Record:
      properties:
        key:
          type: string
        value:
          type: buffer
        headers:
          type: array
          items:
            $ref: "#/components/schemas/Record"
      description: A plain key/value record.
```

see:

```
❯ xtp plugin init --schema-file ./rr.yaml --template go --path rr -y
Error: failed to render template: Uncaught TypeError: ejs:5
    3|
    4| import (
 >> 5| 	<% if (JSON.stringify(schema).includes("enum")) { %>"errors"<% } %>
    6| 	<% if (JSON.stringify(schema).includes("date-time")) { %>"time"<% } %>
    7|
    8| 	pdk "github.com/extism/go-pdk"

circular reference
    at stringify (native)
    at anonymous (<input>:12)
    at apply (native)
    at anonymous (script.js:640)
    at <anonymous> (script.js:444)
    at render (script.js:996)
```

**Comment by evacchi** [comment]
I can take a look at it later, the other backends seem to be handling it well

**Comment by nilslice** [comment]
huh that's strange! I'll take a look today.

**Comment by nilslice** [comment]
This happens in other bindgens where I naively use stringify + includes to check for various types. I'll have to move this out into a helper function and be more specific about the check.

**Comment by mhmd-azeez** [comment]
Circular references are actually not allowed currently. But I had forgotten to add the check for array item references in the current schema plugin (this is fixed in the TS impl). The reason for not allowing them was the fact that the json serializer was crashing when serializing the denormalized xtp schema

**Comment by nilslice** [comment]
Thanks, @mhmd-azeez - I will hold off on this until the validation is present in the CLI and test that this is caught by failing validation.
