### ISSUE TITLE
implement `date-time` format encoding/decoding

### ISSUE THREAD

**Issue by nilslice** [dylibso/xtp-go-bindgen#3]
Could use more detail from @bhelx

**Comment by nilslice** [comment]
(reassigning to me, since I'm in the code today anyways!)

**Comment by bhelx** [comment]
I seem to recall closing another ticket from this recently. Long story short, the plan is to support iso8601 strings. And we will only support `date-time` for now and not the plain `date`. I think you can accomplish this by making some kind of XtpDateTime type or something and writing custom marshal and unmarshal.

**Comment by nilslice** [comment]
In progress in #9
