### ISSUE TITLE
confirm config.yaml is correct

### ISSUE THREAD

**Issue by nilslice** [dylibso/xtp-go-bindgen#7]
Currently, the `init` using the latest bundle prompts with this screen regarding the feature flag used: 
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/0ece04cf-8620-4b64-9b45-46f6bc223735">

But, there is no way to toggle anything. This is using the latest uploaded `xtp` cli build (xtp version 0.0.0+f889800)

**Comment by mhmd-azeez** [comment]
The config.yaml file is correct and seems to be rendered properly on my machine 

![image](https://github.com/user-attachments/assets/942968b5-6525-444c-acbd-296542fe7271)

```
❯ cd ~/.config/xtp/templates/dylibso/xtp-go-bindgen/v0.0.1-rc6
❯ cat config.yaml
template-suffix: ejs
dependencies:
  - tinygo

available-feature-flags:
  - name: stub-with-code-samples
    description: |
      Stub the `main.ts` implementations with code from the codeSamples property.
      By default the implementations will throw a not-implemented error. This will error out
      if every export doesn't have at least one typescript codeSample.
❯ xtp plugin init --template go
   Select feature flags

  1 item

  > 1.  [ ] stub-with-code-samples
            Stub the `main.ts` implementations with code from the codeSamples property.
            By default the implementations will throw a not-implemented error. This will error out
            if every export doesn't have at least one typescript codeSample.















  ↑/k up • ↓/j down • / filter • q quit • ? more

Press SPACE to toggle a feature flag
Press ENTER to confirm the feature flags
Note: You can pass in --feature none to disable all feature flags
```

**Comment by mhmd-azeez** [comment]
Okay, I think I know what's going on. It seems like your terminal is not tall enough and the screen gets cropped (bubbletea can't render the entire view). I will decrease the list height

**Comment by nilslice** [comment]
That is definitely the cause! Good thinking 🧠
